[package]
name = "jito-protos"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bytes = "1.4.0"
prost = "0.13"
prost-types = "0.13"
solana-perf = "=2.1"
solana-sdk = "=2.1"
tonic = "0.13"

[build-dependencies]
tonic-build = "0.13"
